### PR TITLE
Adding KAFKA_SERVICE var

### PR DESCRIPTION
**Pull request by gregmccoy**
Adding KAFKA_SERVICE to the appConfig. My editor auto strips whitespace sorry if that is annoying

### CODE REVIEW

**Comment by vbezbakh-indocsystems** [comment]
@gregmccoy Please follow [README.md](https://github.com/PilotDataPlatform/helm-charts/blob/main/README.md) to package helm-charts

**Comment by gregmccoy** [comment]
@vbezbakh-indocsystems Tried following the instructions there swapping out `mychart` for `workspace-service`. The result creates a lot of changes that does not  look remotely correct including erasing the variable I'm trying to add.

**Comment by vbezbakh-indocsystems** [comment]
@gregmccoy Please take a look on the examples of successful updates that can be found in merged PRs in this repository, For example: https://github.com/PilotDataPlatform/helm-charts/pull/157

**Comment by vbezbakh-indocsystems** [comment]
@gregmccoy Can you please package notification service as well?

**Comment by gregmccoy** [comment]
sorry forgot that one, done now

**Pull request merged**
